//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package nabhack.localz.activity;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;
import android.widget.TextView;
import nabhack.localz.LocalzApp;
import nabhack.localz.R.layout;

public final class DealDetailsFragment_
    extends DealDetailsFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        application = ((LocalzApp) getActivity().getApplication());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        details = ((TextView) findViewById(nabhack.localz.R.id.details));
        image = ((WebView) findViewById(nabhack.localz.R.id.image));
        setupView();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_deal_details, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static DealDetailsFragment_.FragmentBuilder_ builder() {
        return new DealDetailsFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public DealDetailsFragment build() {
            DealDetailsFragment_ fragment_ = new DealDetailsFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
