//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package nabhack.localz.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentActivity;
import android.support.v4.view.ViewPager;
import android.util.Log;
import android.view.KeyEvent;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import com.google.android.gms.maps.SupportMapFragment;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import nabhack.localz.LocalzApp;
import nabhack.localz.R.layout;

public final class DealDetailsActivity_
    extends DealDetailsActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_deal_details);
    }

    private void init_(Bundle savedInstanceState) {
        application = ((LocalzApp) this.getApplication());
    }

    private void afterSetContentView_() {
        viewPager = ((ViewPager) findViewById(nabhack.localz.R.id.pager));
        mapFragment = ((SupportMapFragment) findSupportFragmentById(nabhack.localz.R.id.shop_map));
        setupView();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static DealDetailsActivity_.IntentBuilder_ intent(Context context) {
        return new DealDetailsActivity_.IntentBuilder_(context);
    }

    private Fragment findSupportFragmentById(int id) {
        if (!(this instanceof FragmentActivity)) {
            return null;
        }
        FragmentActivity activity_ = ((FragmentActivity) this);
        return activity_.getSupportFragmentManager().findFragmentById(id);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(nabhack.localz.R.menu.deal_details, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public void promptUserToPostDetailOnfacebook() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    DealDetailsActivity_.super.promptUserToPostDetailOnfacebook();
                } catch (RuntimeException e) {
                    Log.e("DealDetailsActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void showFacebookShareToast() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    DealDetailsActivity_.super.showFacebookShareToast();
                } catch (RuntimeException e) {
                    Log.e("DealDetailsActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, DealDetailsActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public DealDetailsActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
