//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package nabhack.localz.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.view.WindowManager;
import android.widget.ImageView;
import android.widget.TextView;
import nabhack.localz.LocalzApp;
import nabhack.localz.R.id;
import nabhack.localz.R.layout;

public final class RedeemActivity_
    extends RedeemActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_redeem);
    }

    private void init_(Bundle savedInstanceState) {
        injectExtras_();
        windowsManager = ((WindowManager) this.getSystemService(Context.WINDOW_SERVICE));
        application = ((LocalzApp) this.getApplication());
    }

    private void afterSetContentView_() {
        dealTitle = ((TextView) findViewById(id.deal_title));
        qrImageView = ((ImageView) findViewById(id.qrcode_image_view));
        initDisplay();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static RedeemActivity_.IntentBuilder_ intent(Context context) {
        return new RedeemActivity_.IntentBuilder_(context);
    }

    @SuppressWarnings("unchecked")
    private<T >T cast_(Object object) {
        return ((T) object);
    }

    private void injectExtras_() {
        Intent intent_ = getIntent();
        Bundle extras_ = intent_.getExtras();
        if (extras_!= null) {
            if (extras_.containsKey("dealid")) {
                try {
                    dealid = cast_(extras_.get("dealid"));
                } catch (ClassCastException e) {
                    Log.e("RedeemActivity_", "Could not cast extra to expected type, the field is left to its default value", e);
                }
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, RedeemActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public RedeemActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

        public RedeemActivity_.IntentBuilder_ dealid(String dealid) {
            intent_.putExtra("dealid", dealid);
            return this;
        }

    }

}
